# Generated by Django 5.2 on 2025-12-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='display_key',
            field=models.CharField(blank=True, help_text='Key/path of the display-sized image in object storage.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_key',
            field=models.CharField(blank=True, help_text='Key/path of the thumbnail image in object storage.', max_length=512, null=True),
        ),
    ]
