# Generated by Django 5.2 on 2025-11-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_key',
        ),
    ]
