# Generated by Django 5.2 on 2025-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail_key',
            field=models.CharField(blank=True, help_text='Key/path of the thumbnail in object storage (S3/Minio).', max_length=512),
        ),
    ]
