# Generated by Django 5.2 on 2025-12-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_photo_content_type_remove_photo_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
