# Generated by Django 5.2 on 2025-12-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_add_thumbnail_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fullscreen_key',
            field=models.CharField(blank=True, help_text='Key/path of the fullscreen image in object storage (S3/Minio).', max_length=512),
        ),
    ]
