# Generated by Django 5.2 on 2025-12-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_content_type_photo_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
