# Generated by Django 5.2 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_moderated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='moderated',
        ),
        migrations.AddField(
            model_name='photo',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
